version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - net

  php:
    image: php:7.4-fpm-alpine
    container_name: php
    expose:
      - 9000
    volumes:
      - ./public_html:/var/www/html
    networks:
      - net
    depends_on:
      - mysql

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./public_html:/var/www/html
    networks:
      - net
    depends_on:
      - mysql
      - php
  

  
networks:
  net:
    driver: bridge
